heat_template_version: 2016-04-08
#
# you can deploy this template using the following command:
# 'openstack stack create -t 02b_routed_network.yaml <stack_name>'
# 

description: deploys a network environment with router, floating ip and security group. 

parameters:
 public_network_id:
  type: string
  default: caf8de33-1059-4473-a2c1-2a62d12294fa 
            
resources:
  example_net:
    type: OS::Neutron::Net
    properties: 
      name: management network

  example_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: management subnet
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/8
      allocation_pools:
      - {start: 10.0.0.10, end: 10.255.255.250}

  example_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network_id }}
      name: example network router

  example_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: example_subnet
    properties:
      router: { get_resource: example_router }
      subnet: { get_resource: example_subnet }

  example_node_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: example_net}
      security_groups: [{ get_resource: example_security_group }]

  example_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: example_node_port }

